// build-site.mjs — assembles site/, a static build for GitHub Pages (npm run site).
//
// The static build contains NO API key and makes no provider call. Visitors get:
//   • the recorded demo session (real DeepSeek output, captured once and replayed read-only),
//   • offline template mode, where the real pipeline and integrity guard run in their browser,
//   • the teacher task designer and class overview, which were always browser-only.
// To run live feedback they download the release zip and use their own key, or you deploy the proxy in
// worker/ and set ARGUMENTOR_API below.
//
//   node build-site.mjs                      → offline-only site
//   node build-site.mjs --api https://…      → same site, pointed at your deployed proxy
import { readFile, writeFile, mkdir, rm, cp } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { APP_VERSION } from './core.mjs';

const ROOT = dirname(fileURLToPath(import.meta.url));
const OUT = join(ROOT, 'site');
const args = process.argv.slice(2);
const apiIndex = args.indexOf('--api');
const API = apiIndex >= 0 ? String(args[apiIndex + 1] || '').replace(/\/+$/, '') : '';

// Browser modules only: nothing here imports node:*, and server.mjs/provider.mjs/setup.mjs are excluded
// precisely because they are the parts that would ever touch a key.
const MODULES = ['app.mjs', 'core.mjs', 'engine.mjs', 'orchestrator.mjs', 'prompts.mjs', 'guard.mjs', 'mock.mjs', 'sha256.mjs', 'html.mjs', 'i18n.mjs', 'api.mjs', 'diff.mjs', 'report.mjs', 'teacher.mjs'];
const ASSETS = ['styles.css', 'favicon.svg'];

const banner = (zh, en) => `<div class="site-note"><strong>${zh}</strong><span>${en}</span></div>`;

function indexHtml() {
  const csp = [
    "default-src 'self'", "script-src 'self'", "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data:", `connect-src 'self'${API ? ` ${API}` : ''}`,
    // frame-ancestors is ignored in a <meta> CSP (header-only), so it is left out rather than logged as an error.
    "base-uri 'none'", "form-action 'none'", "object-src 'none'"
  ].join('; ');
  return `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#164c45">
  <meta http-equiv="Content-Security-Policy" content="${csp}">
  <meta name="description" content="ArguMentor 论证工坊: a multi-agent Socratic coach for English argumentative writing. Demo and offline mode; no API key required.">
  <title>论证工坊 · ArguMentor</title>
  <link rel="icon" href="./favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="./styles.css">
  <style>
    .site-note { max-width: 1440px; margin: 10px auto 0; padding: 10px 32px; font-size: .82rem; color: #2e5444; display: grid; gap: 2px; }
    .site-note strong { font-weight: 650; }
    .site-note span { color: #5b6d66; }
    @media (max-width: 860px) { .site-note { padding: 10px 16px; } }
  </style>
</head>
<body>
  <a class="skip" href="#workspace">跳转到工作区 / Skip to workspace</a>
  ${API ? '' : banner(
    '这是公开演示站：可回放真实录制的 DeepSeek 会话，也可用离线模板模式走完整流程（不调用任何 AI，不需要密钥）。',
    'Public demo build: replay the recorded DeepSeek session, or walk the full workflow in offline template mode. No AI call is made and no API key is needed. For live feedback, download the release and run it with your own key.')}
  <div id="app"><noscript>论证工坊需要启用 JavaScript。/ ArguMentor needs JavaScript.</noscript></div>
  <div id="toast" role="status" aria-live="polite"></div>
  <div id="live" class="sr-only" aria-live="polite"></div>
  <dialog class="dialog" id="dialog" aria-label="ArguMentor"></dialog>
  <!-- An external module, not an inline script, so the page's own script-src 'self' policy holds. -->
  <script type="module" src="./config.mjs"></script>
  <script type="module" src="./app.mjs"></script>
</body>
</html>
`;
}

const README = `# ArguMentor — static build

Generated by \`npm run site\` from ArguMentor ${APP_VERSION}. **Contains no API key and no server code.**

- \`index.html?demo=1\` replays the recorded DeepSeek session (read-only).
- Without \`?demo=1\`, the app runs in **offline template mode**: the real orchestrator, prompts and
  integrity guard execute in the browser against fixed templates, so the workflow is complete but the
  feedback is not AI-generated. The interface says so.
- The teacher task designer and class overview work fully; they were always browser-only.

For live AI feedback, download the release zip and run it locally with your own DeepSeek key,
or deploy \`worker/\` and rebuild with \`node build-site.mjs --api https://your-worker.example\`.
`;

await rm(OUT, { recursive: true, force: true });
await mkdir(join(OUT, 'demo'), { recursive: true });
for (const file of [...MODULES, ...ASSETS]) await cp(join(ROOT, file), join(OUT, file));
for (const file of ['ai-classroom.json', 'task-ai-classroom.json', 'workplace-ai-monitoring.json', 'task-workplace-ai.json']) await cp(join(ROOT, 'demo', file), join(OUT, 'demo', file));
await writeFile(join(OUT, 'index.html'), indexHtml());
// Deployment configuration as a module file. It carries no secret: either a public proxy URL, or a flag
// saying there is no back end at all, so api.mjs skips probing an endpoint it knows is absent.
await writeFile(join(OUT, 'config.mjs'), API
  ? `// Hosted build: requests go to the proxy, which holds the API key as a platform secret.\nglobalThis.ARGUMENTOR_API = ${JSON.stringify(API)};\n`
  : '// Offline build: no back end. The pipeline runs in this browser against the template provider.\nglobalThis.ARGUMENTOR_OFFLINE = true;\n');
await writeFile(join(OUT, 'README.md'), README);
await writeFile(join(OUT, '.nojekyll'), ''); // GitHub Pages: serve files as-is

// A build that shipped a key would be a catastrophe, so fail loudly rather than quietly.
const SECRET = /\bsk-[A-Za-z0-9]{20,}\b/;
for (const file of [...MODULES, 'index.html', 'config.mjs']) {
  if (SECRET.test(await readFile(join(OUT, file), 'utf8'))) throw new Error(`Refusing to build: ${file} looks like it contains an API key.`);
}

console.log(`Built site/ (${MODULES.length + ASSETS.length + 4} files) — ${API ? `proxy: ${API}` : 'offline only, no back end'}.`);
console.log('Publish it with GitHub Pages, or preview locally:  cd site && python3 -m http.server 8080');
